name: example deploy

on:
  push:
    branches: [fix/deploy-example]
jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
      - name: Build library
        - run: pnpm --dir ./packages/examples run build
      - name: Init new repo in dist folder and commit generated files
        run: |
          git init
          cd  packages/examples
          pnpm install
          pnpm build
          cp -R dist ../../docs
          git add -f ../../docs
          git config --local user.email "romankalugernovoros@gmail.com"
          git config --local user.name "Roman Kaluger"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: packages/examples/dist
