name: examples

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        example:
          - simple

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install lib dependencies
        run: yarn --frozen-lockfile
      - name: Build lib
        run: yarn build
      - name: Install dependencies of example ${{ matrix.example }}
        run: (cd example/${{ matrix.example }} && yarn --frozen-lockfile)
      - name: Building example ${{ matrix.example }}
        run: (cd example/${{ matrix.example }} && yarn build)
